### ISSUE TITLE
[PE-D] No response when I try to enter "policy 6 insurer/AIG num/9999999999 n/Critical illness comm/100"

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-T14-4/tp#136]
![image.png](https://raw.githubusercontent.com/jiayi1129/ped/main/files/9dcadf41-dbd6-4c34-8654-565be7564733.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: jiayi1129/ped#7

**Comment by mokdarren** [comment]
* Allow edits on details tab
* Change policy id to allow value up to long max value
