### ISSUE TITLE
[PE-D] Recurring events do not start on intended date

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-T14-4/tp#137]
From an empty list of events (so no clashes with other events), when entering command `add d/meeting date/18-05-2021 fr/1600 to/1800 t/priority recurw/15-08-2021`, the expected first event is 18 May 2021 and the expected subsequent events are on 25 May, 1 June, 8 June, 15 June, 22 June, 29 June, 6 July, 13 July, 20 July, 27 July, 3 August and 8 August, a total of 13 events. However, only the last 2 events show up in my schedule despite the lack of any event clashes.

![Screenshot 2021-10-29 at 4.38.06 PM.png](https://raw.githubusercontent.com/kleonang/ped/main/files/b8f73ac4-c2ef-42d5-8e26-e15f033bff4f.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: kleonang/ped#3

**Comment by rickyaandrew** [comment]
This is working fine. user probably did not list all the events because they are all past events.
