### ISSUE TITLE
[PE-D] There should be multidelete or multiedit or clear for recurring events

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-T14-4/tp#139]
Since you have a recurring events option, if I add a date quite far away, the events list is spammed with many events. Let's say I wrongly added one parameter and want to delete or edit this event for all recurring values. But there is no way of multidelete or multiedit or clearing the whole list at once. This should probably be implemented because deleting or editing one by one is a pain.

![Screenshot 2021-10-29 at 4.41.53 PM.png](https://raw.githubusercontent.com/rebeccacxy/ped/main/files/f392b49e-2e2e-4321-8ce3-a9d16bdaf589.png)Screenshot 2021-10-29 at 4.41.53 PM

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: rebeccacxy/ped#10

**Comment by whoisjustinngo** [comment]
@rickyaandrew maybe can add potential feature in UG
