### ISSUE TITLE
[PE-D] Finding events do not detect substring matches

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-T14-4/tp#146]
Might be better to allow find to detect substrings (e.g. for event titled “meeting”, allowing someone to search for the event by finding “meet” might be a good idea)

If there's one event titled "meeting" as shown below:

![Screenshot 2021-10-29 at 4.15.33 PM.png](https://raw.githubusercontent.com/kleonang/ped/main/files/03d95158-f390-4f91-bfc8-09e76b4e4ab0.png)

Finding on "meet" returns no results:

![Screenshot 2021-10-29 at 4.15.37 PM.png](https://raw.githubusercontent.com/kleonang/ped/main/files/d9d8a312-2082-40b3-8b71-bb3a2d7a532e.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: kleonang/ped#5

**Comment by rickyaandrew** [comment]
Dont think this is a bug. this means that we need to search letter by letter for all find and filter commands
