### ISSUE TITLE
[PE-D] Inconsistent param names

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-T14-4/tp#155]
I think the inconsistent param names, some being a single letter, others being words, others being rather strange-looking words that are not in dictionary (eg. recurw) will compromised user experience greatly

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: samyipsh/ped#4

**Comment by whoisjustinngo** [comment]
Unable to change due to feature freeze
