### ISSUE TITLE
[PE-D] "Q4 values" tab is confusing and I am unsure how it is updated

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-T14-4/tp#173]
As someone who doesn't work with finance, I am very confused by what the "Q4 values" do and there is no mention of this in the UG. I understand these are stats but as I add more goals with different dates on the dashboard, the last 4 fields remain as `0` (is this buggy?) I am not sure how they are updated.

I believe some explanation on this in the UG is definitely needed.

![Screenshot 2021-10-29 at 4.25.26 PM.png](https://raw.githubusercontent.com/rebeccacxy/ped/main/files/e9271e87-1e99-4b59-a232-313a627e624c.png)Screenshot 2021-10-29 at 4.25.26 PM

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: rebeccacxy/ped#7

**Comment by whoisjustinngo** [comment]
Analytics description added to UG
