### ISSUE TITLE
Client status description in UG

### ISSUE THREAD

**Issue by whoisjustinngo** [AY2122S1-CS2103-T14-4/tp#180]
It would be good to include a short explanation as to how we intend for the user to use the various client status (fresh, negotiated etc), which affects their user experience for the dashboard analytics feature. I have included a short writeup about how the analytics work (just summing up by the different statuses), and have referred the user to the contacts section for more info about the various statuses (how to add, edit etc).

**Comment by mokdarren** [comment]
completed (in draft PR)
